services:
  - type: web
    name: lms-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn lms_backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: lms_backend.settings
      - key: PYTHON_VERSION
        value: 3.12